/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/configuration/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getEnv']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAllUserConversations']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations/{conversationId}': {
    parameters: {
      query?: never
      header?: never
      path: {
        conversationId: string
      }
      cookie?: never
    }
    get: operations['getSingleConversation']
    put?: never
    post?: never
    delete: operations['deleteConversation']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/conversations/{conversationId}/messages': {
    parameters: {
      query?: never
      header?: never
      path: {
        conversationId: string
      }
      cookie?: never
    }
    get: operations['getConversationHistory']
    put?: never
    post: operations['streamGeneration']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/payments/subscriptions/trial': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['newSubscriptionWithTrial']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/users/complete-onboarding': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['completeOnboarding']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/users/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getUser']
    put: operations['updateUser']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/webhook/stripe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['handleStripeWebhook']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AssistantMessage: {
      media: components['schemas']['Media'][]
      /** @enum {string} */
      messageType: 'USER' | 'ASSISTANT' | 'SYSTEM' | 'TOOL'
      metadata: {
        [key: string]: Record<string, never>
      }
      text: string
      toolCalls: components['schemas']['ToolCall'][]
    }
    ChatGenerationMetadata: {
      contentFilters: string[]
      empty: boolean
      finishReason: string
    }
    ChatResponse: {
      metadata: components['schemas']['ChatResponseMetadata']
      result: components['schemas']['Generation']
      results: components['schemas']['Generation'][]
    }
    ChatResponseMetadata: {
      empty: boolean
      id: string
      model: string
      promptMetadata: components['schemas']['PromptMetadata']
      rateLimit: components['schemas']['RateLimit']
      usage: components['schemas']['Usage']
    }
    ChatStreamResponseDTO: {
      chatResponse: components['schemas']['ChatResponse']
      conversationId: string
      /** Format: int64 */
      timestamp: number
    }
    Configuration: {
      oauthBaseUrl: string
      oauthSignInRedirectUrl: string
      oauthSignInUrl: string
      oauthSignOutRedirectUrl: string
      oauthSignOutUrl: string
      publicPostHogHost: string
      publicPostHogKey: string
      stripeBillingPortalCode: string
      stripePriceIdBasic: string
      stripePriceIdFree: string
      stripePriceIdPremium: string
    }
    ConversationDTO: {
      conversationId: string
      title: string
    }
    EntityTag: {
      value: string
      weak: boolean
    }
    Generation: {
      metadata: components['schemas']['ChatGenerationMetadata']
      output: components['schemas']['AssistantMessage']
    }
    Link: {
      params: {
        [key: string]: string
      }
      rel: string
      rels: string[]
      title: string
      type: string
      /** Format: uri */
      uri: string
      uriBuilder: components['schemas']['UriBuilder']
    }
    LLMRequest: {
      userInput: string
    }
    Media: {
      data: Record<string, never>
      /** Format: byte */
      dataAsByteArray: string
      id: string
      mimeType: components['schemas']['MimeType']
      name: string
    }
    MediaType: {
      parameters: {
        [key: string]: string
      }
      subtype: string
      type: string
      wildcardSubtype: boolean
      wildcardType: boolean
    }
    MessageDTO: {
      message: string
      /** @enum {string} */
      messageType: 'USER' | 'ASSISTANT' | 'SYSTEM' | 'TOOL'
      /** Format: date-time */
      timestamp: string
    }
    MimeType: {
      charset: string
      concrete: boolean
      parameters: {
        [key: string]: string
      }
      subtype: string
      subtypeSuffix: string
      type: string
      wildcardSubtype: boolean
      wildcardType: boolean
    }
    NewCookie: {
      comment: string
      domain: string
      /** Format: date-time */
      expiry: string
      httpOnly: boolean
      /** Format: int32 */
      maxAge: number
      name: string
      path: string
      /** @enum {string} */
      sameSite: 'NONE' | 'LAX' | 'STRICT'
      secure: boolean
      value: string
      /** Format: int32 */
      version: number
    }
    PromptMetadata: Record<string, never>
    RateLimit: {
      /** Format: int64 */
      requestsLimit: number
      /** Format: int64 */
      requestsRemaining: number
      requestsReset: {
        /** Format: int32 */
        nano: number
        negative: boolean
        positive: boolean
        /** Format: int64 */
        seconds: number
        units: {
          dateBased: boolean
          durationEstimated: boolean
          timeBased: boolean
        }[]
        zero: boolean
      }
      /** Format: int64 */
      tokensLimit: number
      /** Format: int64 */
      tokensRemaining: number
      tokensReset: {
        /** Format: int32 */
        nano: number
        negative: boolean
        positive: boolean
        /** Format: int64 */
        seconds: number
        units: {
          dateBased: boolean
          durationEstimated: boolean
          timeBased: boolean
        }[]
        zero: boolean
      }
    }
    Response: {
      allowedMethods: string[]
      closed: boolean
      cookies: {
        [key: string]: components['schemas']['NewCookie']
      }
      /** Format: date-time */
      date: string
      entity: Record<string, never>
      entityTag: components['schemas']['EntityTag']
      headers: {
        empty: boolean
      } & {
        [key: string]: Record<string, never>[]
      }
      language: {
        country: string
        displayCountry: string
        displayLanguage: string
        displayName: string
        displayScript: string
        displayVariant: string
        extensionKeys: string[]
        iso3Country: string
        iso3Language: string
        language: string
        script: string
        unicodeLocaleAttributes: string[]
        unicodeLocaleKeys: string[]
        variant: string
      }
      /** Format: date-time */
      lastModified: string
      /** Format: int32 */
      length: number
      links: components['schemas']['Link'][]
      /** Format: uri */
      location: string
      mediaType: components['schemas']['MediaType']
      metadata: {
        empty: boolean
      } & {
        [key: string]: Record<string, never>[]
      }
      /** Format: int32 */
      status: number
      statusInfo: components['schemas']['StatusType']
      stringHeaders: {
        empty: boolean
      } & {
        [key: string]: string[]
      }
    }
    StatusType: {
      /** @enum {string} */
      family:
        | 'INFORMATIONAL'
        | 'SUCCESSFUL'
        | 'REDIRECTION'
        | 'CLIENT_ERROR'
        | 'SERVER_ERROR'
        | 'OTHER'
      reasonPhrase: string
      /** Format: int32 */
      statusCode: number
    }
    ToolCall: {
      arguments: string
      id: string
      name: string
      type: string
    }
    UriBuilder: Record<string, never>
    Usage: {
      /** Format: int32 */
      completionTokens: number
      nativeUsage: Record<string, never>
      /** Format: int32 */
      promptTokens: number
      /** Format: int32 */
      totalTokens: number
    }
    UserDTO: {
      country: string
      email: string
      firstName: string
      hasCompletedOnboarding: boolean
      id: string
      lastName: string
      locality: string
      password: string
      phone: string
      postalCode: string
      region: string
      street: string
      /** @enum {string} */
      tier: 'FREE' | 'TIER1' | 'TIER2' | 'ENTERPRISE' | 'UNLIMITED'
      userName: string
      verified: boolean
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getEnv: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Configuration']
        }
      }
    }
  }
  getAllUserConversations: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ConversationDTO'][]
        }
      }
    }
  }
  getSingleConversation: {
    parameters: {
      query?: never
      header?: never
      path: {
        conversationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ConversationDTO']
        }
      }
    }
  }
  deleteConversation: {
    parameters: {
      query?: never
      header?: never
      path: {
        conversationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getConversationHistory: {
    parameters: {
      query?: never
      header?: never
      path: {
        conversationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MessageDTO'][]
        }
      }
    }
  }
  streamGeneration: {
    parameters: {
      query?: never
      header?: never
      path: {
        conversationId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LLMRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': components['schemas']['ChatStreamResponseDTO'][]
        }
      }
    }
  }
  newSubscriptionWithTrial: {
    parameters: {
      query?: never
      header: {
        'X-priceId': string
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  completeOnboarding: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Response']
        }
      }
    }
  }
  getUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserDTO']
        }
      }
    }
  }
  updateUser: {
    parameters: {
      query: {
        user: components['schemas']['UserDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Response']
        }
      }
    }
  }
  handleStripeWebhook: {
    parameters: {
      query?: never
      header: {
        'Stripe-Signature': string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': string
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
}
