FROM eclipse-temurin:24-jre
WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends curl \
  && rm -rf /var/lib/apt/lists/*

COPY build/libs/*.jar /app/app.jar

EXPOSE 8083

ENV JAVA_OPTS="-XX:MaxRAMPercentage=75"

CMD ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
