name: Web Pipeline

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm

      - id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: pnpm install --frozen-lockfile

      - name: Build web app
        run: pnpm run build --filter=web

      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/web/dist
          retention-days: 1

  docker-build:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          IMAGE_TAG="${{ github.run_number }}-${SHORT_SHA}"
          echo "FRONTEND_IMAGE=${{ secrets.NEXUS_DOCKER_URL }}/frontend:${IMAGE_TAG}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - name: Build Web Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: false
          tags: ${{ env.FRONTEND_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=web-image.tar

      - name: Compress image
        run: gzip web-image.tar

      - uses: actions/upload-artifact@v4
        with:
          name: web-docker-image
          path: web-image.tar.gz
          retention-days: 1
